services:
  db:
    image: postgres:16-alpine
    container_name: pullsheets-db
    environment:
      POSTGRES_USER: pullsheets
      POSTGRES_PASSWORD: pullsheets
      POSTGRES_DB: pullsheets
    ports:
      - '5432:5432'
    volumes:
      - pullsheets-pg:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pullsheets']
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pullsheets-pg:
